name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - 'releases/*'

jobs:
  test-jacoco-report-parser:
    name: Jacoco Reprot Parse
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          path: target/site/jacoco/jacoco.csv

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.instruction_count }}"
          echo "${{ steps.test-action.outputs.instruction_covered }}"
          echo "${{ steps.test-action.outputs.instruction_coverage }}"
          echo "${{ steps.test-action.outputs.lines_count }}"
          echo "${{ steps.test-action.outputs.lines_covered }}"
          echo "${{ steps.test-action.outputs.lines_coverage }}"
          echo "${{ steps.test-action.outputs.method_count }}"
          echo "${{ steps.test-action.outputs.method_covered }}"
          echo "${{ steps.test-action.outputs.method_coverage }}"
          echo "${{ steps.test-action.outputs.class_cunt }}"
